
ckpt_dir: ./ckpts
output_dir: ./outputs
sample_steps: 50
solver_name: unipc
model_name: "720x720_5s" # ["720x720_5s", "960x960_5s", "960x960_10s"]
shift: 5.0
sp_size: 1
audio_guidance_scale: 3.0
video_guidance_scale: 4.0
mode: "i2v" # ["t2v", "i2v", "t2i2v"] all comes with audio
fp8: True
cpu_offload: True
seed: 103
video_negative_prompt: "jitter, bad hands, blur, distortion"  # Artifacts to avoid in video
audio_negative_prompt: "robotic, muffled, echo, distorted"    # Artifacts to avoid in audio
video_frame_height_width: [720, 720] # must match the target area for the selected model (720x720_5s â†’ 720x720)
text_prompt: "Describe your video prompt here."
slg_layer: 11
each_example_n_times: 2
